#!/usr/bin/env perl

use Modern::Perl;
use DBIx::Class::Schema::Loader 'make_schema_at';

use FindBin;

my $DEBUG = @ARGV and $ARGV[0] =~ /^\-[\-]*v/;

say $DBIx::Class::Schema::Loader::VERSION
	if $DEBUG;
my @dsn = "dbi:SQLite:dbname=$FindBin::Bin/../db/main.db";

my $options = {
  debug          => $DEBUG,
  dump_directory => "$FindBin::Bin/../lib",
  components     => [qw/ InflateColumn::DateTime /],
  generate_pod   => 0,
};

make_schema_at(Schema => $options, \@dsn);
